### ISSUE TITLE
Можно адаптировать для Rails?

### ISSUE THREAD

**Issue by deni5n** [avil13/gulp-templater#1]
Удобно верстать с вашим плагином, но для Rails  после него приходится вносить изменения, которые связаны с условностями самик Рельс. 

1. Если "партиалов"  больше одного - в папку назначения попадают все собранные файлы, когда для верстки нужен только один файл на одну папку, например структура приложения:

App
  views
    layouts                //шаблон
      application.html.erb
    home                  //"партиал"
      index.html.erb
      _content.html.erb
      _form.html.erb
    sessions              //"партиал"
      index.html.erb
      _new.html.erb
      _destroy.html.erb

Типичное для Rails содержание:

application.html.erb:
-------------------------------
<!DOCTYPE html>
<html>
  <head>  </head>
  <body>
    <%= yield %>
  </body>
</html>

вместо  <%= yield %>  подставляется например содержимое файла home/index.html.erb:

файл  home/index.html.erb
------------------------------------
<%= render 'home/content' %>

файл  home/_content.html.erb
------------------------------------
<%= render 'home/form' %>

В вашем плагине такая структура приведет к созданию всех папок и файлов в папке назначения. Для проектов Rails достаточно двух собранных файлов application.home.html и application.session.html. Если папок (home session) больше двух, например есть еще папка admin, то соотвествтенно должен собраться еще один файл application.admin.html.erb. Остальные файлы в папку назначения не должны попадать, хотя и должны рендерится чтобы развязать все зависимости.

итоговый вид папки назначения:

App
  views
    dest
      application.home.html.erb
      application.session.html.erb

Вы можете учесть это в плагине? 

2. Шаблоны вставляются через <%%>. Для приложения на Rails шаблоны выглядят как <%= render "папка с партиалом/партиал"%> На базе структуры папок из примера выше шаблон index.html.erb из папки home включающий два файла: _content.html.erb и _form.html.erb выглядит так:

файл  home/index.html.erb
------------------------------------
<%= render 'home/content' %>

файл  home/_content.html.erb
------------------------------------
<%= render 'home/form' %>

это еще один способ вставки файлов в файлы в rails, через render. 

Вы можете учесть это в плагине?

В этом вопросе есть еще одна особенность текущей версии плагина - если между "this" и "%%" стоят пробел, как в примере: <%% this %%> - шаблон не собирается из за пробелов. Мне кажется нужно удалять пробелы автоматически при сборке, т.к. человеку удобнее читать текст с пробелами.

Вы можете учесть это в плагине?  

Много букв, но думаю те кто используют rails скажут вам большое спасибо за такой удобный плагин! 

P.S. Сам я его написать не могу - нет опыта работы с JS, чтобы написать плагин ((

**Comment by avil13** [comment]
Спасибо, за отзыв.
Постараюсь применить ваши пожелания в ближайшее время по мере возможностей.

**Comment by avil13** [comment]
@deni5n не мог бы ты создать репозиторий с примером того, как у тебя строятся папки и файлы и оставить здесь ссылку.
На его реальном примере я бы попробовал внести улучшения в плагин.

**Comment by deni5n** [comment]
Добрый день,
создал репозитарий https://github.com/deni5n/template.git
Спасибо !
если возникнут вопросы - deni5n@yandex.ru

**Comment by avil13** [comment]
@deni5n сорри, но совершенно не нахожу времени заняться плагином.
Уже знаю как его переделаю, но это займет много времени так как переписать его надо весь.
Возможно вам может помочь один из этих плагинов:
- https://github.com/alanshaw/grunt-include-replace
- https://github.com/spatools/grunt-html-build
- Вот тут сразу два варианта рещения https://habrahabr.ru/post/270161/
